frontend:
  build: frontend
  ports:
    - "7000:80"
  volumes:
    - frontend/dist:/usr/share/nginx/html
  links:
    - backend

backend:
  build: backend
  ports:
    - "8000:8000"
  volumes:
    - backend:/usr/src/app

